version: '3'

services:
  api:
    build: .
    restart: always
    privileged: true
    environment:
      - APP_NAME
      - DATABASE_CLIENT
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_NAME
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
    ports:
      - 1337:1337
    volumes:
      - ./strapi-app:/usr/src/api/strapi-app
      # - /usr/src/api/strapi-app/node_modules
